# run_main_from_csv_parallel.py
# python run_main_from_csv_parallel.py --input-csv "out.csv" --main-script "D:\INIA_CODE\INIA_Puno_Software_v1.0.0.2\INIA_Software\main.py" --resultados-excel "D:\INIA_CODE\INIA_Puno_Software_v1.0.0.2\INIA_Software\RESULTADOS USUARIOS 2M_Illpa 2.0.2.xlsx" --template-excel "D:\INIA_CODE\INIA_Puno_Software_v1.0.0.2\INIA_Software\Software_Mejorado_Cultivos_Anuales_2025-2026_Arapa.xlsx" --report-root "G:\Mi unidad\REPORTES_GENERADOS" --pdf-folder "G:\Mi unidad\LABSAF ILLPA\CAMPAÃ‘A PERU 2M- LABSAF ILLPA\INFORMES DE ENSAYO" --report-script "D:\INIA_CODE\INIA_Puno_Software_v1.0.0.2\INIA_Software\report_pdf.py" --workers 4
from pathlib import Path
import argparse
import csv
import subprocess
import sys
import re
import unicodedata
from concurrent.futures import ProcessPoolExecutor, as_completed


# ------------------------------------------------------------
# Helpers
# ------------------------------------------------------------

def safe_filename(text):
    """
    Convert a person name into a safe filename.
    """
    if text is None:
        return "unknown"

    text = str(text).strip()
    text = unicodedata.normalize("NFKD", text)
    text = "".join(c for c in text if not unicodedata.combining(c))
    text = re.sub(r"[^\w\s-]", "", text)
    text = re.sub(r"\s+", "_", text)

    return text.strip("_") or "unknown"


def read_jobs_from_csv(csv_file):
    """
    Reads CSV with columns:

        NOMBRES Y APELLIDOS
        CULTIVO A INSTALAR
    """
    csv_file = Path(csv_file)

    if not csv_file.exists():
        raise FileNotFoundError(f"CSV file not found: {csv_file}")

    jobs = []

    with open(csv_file, "r", encoding="utf-8-sig", newline="") as f:
        reader = csv.DictReader(f)

        required_columns = [
            "NOMBRES Y APELLIDOS",
            "CULTIVO A INSTALAR",
        ]

        for col in required_columns:
            if col not in reader.fieldnames:
                raise ValueError(
                    f"Missing column in CSV: {col}\n"
                    f"Found columns: {reader.fieldnames}"
                )

        for row in reader:
            name = row.get("NOMBRES Y APELLIDOS", "").strip()
            cultivo = row.get("CULTIVO A INSTALAR", "").strip()

            if not name or not cultivo:
                continue

            jobs.append({
                "name": name,
                "cultivo": cultivo,
            })

    return jobs


def run_one_job(job, args_dict):
    """
    Runs main.py for one person/cultivo.
    """
    name = job["name"]
    cultivo = job["cultivo"]

    logs_dir = Path(args_dict["logs_dir"])
    logs_dir.mkdir(parents=True, exist_ok=True)

    log_file = logs_dir / f"{safe_filename(name)}_{safe_filename(cultivo)}.log"

    command = [
        sys.executable,
        args_dict["main_script"],

        "--resultados-excel",
        args_dict["resultados_excel"],

        "--template-excel",
        args_dict["template_excel"],

        "--name",
        name,

        "--cultivo",
        cultivo,

        "--report-root",
        args_dict["report_root"],

        "--pdf-folder",
        args_dict["pdf_folder"],

        "--report-script",
        args_dict["report_script"],
    ]

    with open(log_file, "w", encoding="utf-8") as log:
        log.write("Running command:\n")
        log.write(" ".join(f'"{x}"' if " " in x else x for x in command))
        log.write("\n\n")

        result = subprocess.run(
            command,
            stdout=log,
            stderr=subprocess.STDOUT,
            text=True,
        )

    return {
        "name": name,
        "cultivo": cultivo,
        "returncode": result.returncode,
        "log_file": str(log_file),
    }


# ------------------------------------------------------------
# Main
# ------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Run main.py in parallel for all rows in a CSV file."
    )

    parser.add_argument(
        "--input-csv",
        required=True,
        help="CSV generated by filter_by_distrito.py.",
    )

    parser.add_argument(
        "--main-script",
        default="main.py",
        help="Path to main.py.",
    )

    parser.add_argument(
        "--resultados-excel",
        required=True,
        help="Input RESULTADOS Excel file.",
    )

    parser.add_argument(
        "--template-excel",
        required=True,
        help="Template Excel file.",
    )

    parser.add_argument(
        "--report-root",
        required=True,
        help="Output folder for generated reports.",
    )

    parser.add_argument(
        "--pdf-folder",
        required=True,
        help="Folder containing original laboratory PDF reports.",
    )

    parser.add_argument(
        "--report-script",
        required=True,
        help="Path to report_pdf.py.",
    )

    parser.add_argument(
        "--workers",
        type=int,
        default=4,
        help="Number of parallel workers. Default: 4.",
    )

    parser.add_argument(
        "--logs-dir",
        default="batch_logs",
        help="Folder where logs will be saved.",
    )

    args = parser.parse_args()

    jobs = read_jobs_from_csv(args.input_csv)

    if not jobs:
        print("No jobs found in CSV.")
        return

    print(f"Jobs found: {len(jobs)}")
    print(f"Running with {args.workers} parallel workers")

    args_dict = {
        "main_script": str(Path(args.main_script)),
        "resultados_excel": str(Path(args.resultados_excel)),
        "template_excel": str(Path(args.template_excel)),
        "report_root": str(Path(args.report_root)),
        "pdf_folder": str(Path(args.pdf_folder)),
        "report_script": str(Path(args.report_script)),
        "logs_dir": str(Path(args.logs_dir)),
    }

    successes = 0
    failures = 0

    with ProcessPoolExecutor(max_workers=args.workers) as executor:
        futures = [
            executor.submit(run_one_job, job, args_dict)
            for job in jobs
        ]

        for future in as_completed(futures):
            result = future.result()

            name = result["name"]
            cultivo = result["cultivo"]
            returncode = result["returncode"]
            log_file = result["log_file"]

            if returncode == 0:
                successes += 1
                print(f"[OK] {name} | {cultivo}")
            else:
                failures += 1
                print(f"[FAILED] {name} | {cultivo}")
                print(f"         Log: {log_file}")

    print()
    print("Batch finished.")
    print(f"Successful: {successes}")
    print(f"Failed: {failures}")
    print(f"Logs folder: {args.logs_dir}")


if __name__ == "__main__":
    main()
